name: Renovate
on:
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 mins
  workflow_dispatch:
  push:
    branches:
      - main
      - deps_check

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v41.0.2
        with:
          token: ${{ secrets.GH_TOKEN }}
          configurationFile: renovate.json
        env:
          LOG_LEVEL: 'debug'
          RENOVATE_AUTODISCOVER: 'false'
          RENOVATE_REPOSITORIES: ${{ github.repository }}
